services:
    app:
        build:
            context: .
        image: imfeelinglucky-app
        container_name: imfeelinglucky-app
        user: 'www-data:www-data'
        volumes:
            - ./app:/var/www/html/app
            - ./config:/var/www/html/config
            - ./database:/var/www/html/database
            - ./public:/var/www/html/public
            - ./resources:/var/www/html/resources
            - ./routes:/var/www/html/routes
            - ./tests:/var/www/html/tests
            - ./composer.json:/var/www/html/composer.json
            - /var/www/html/vendor
        networks:
            - imfeelinglucky-net
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=imfeelinglucky
            - DB_USERNAME=imfeelinglucky
            - DB_PASSWORD=imfeelinglucky
            - REDIS_HOST=redis
            - REDIS_PASSWORD=null
            - REDIS_PORT=6379

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - imfeelinglucky-net
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: imfeelinglucky
            MYSQL_USER: imfeelinglucky
            MYSQL_PASSWORD: imfeelinglucky
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - imfeelinglucky-net

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - imfeelinglucky-net

networks:
    imfeelinglucky-net:
        driver: bridge

volumes:
    db_data:
        driver: local
